import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ADC PROGRAMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://stijndv.com" />
        <link
          rel="stylesheet"
          href="https://stijndv.com/fonts/Eudoxus-Sans.css"
        />
      </Head>
      <div className="p-10 m-3 ">
        <h1 className="text-4xl text-black text-center">SS PROGRAMS</h1>
        <h1 className="text-4xl text-black text-center">
          <Link
            className="text-2xl text-black text-center"
            href="https://wtools.io/paste-code/bOBS"
          >
            AM Modulation and Demodualtion
          </Link>
        </h1>
        <h1 className="text-4xl text-black text-center">
          <Link
            className="text-2xl text-black text-center"
            href="https://wtools.io/paste-code/bOBU"
          >
            FM Modualtion and Demoduation
          </Link>
        </h1>
        <h1 className="text-4xl text-black text-center">
          <Link
            className="text-2xl text-black text-center"
            href="https://wtools.io/paste-code/bOBW"
          >
            DSBSC
          </Link>
        </h1>
        <h1 className="text-4xl text-black text-center">
          <Link
            className="text-2xl text-black text-center"
            href="https://wtools.io/paste-code/bOBX"
          >
            SSBSC
          </Link>
        </h1>
      </div>
    </>
  );
}
